apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: schema-migration-test
  namespace: schema-test-migrate
spec:
  interval: 5m
  url: oci://{{ .DsEcrAccountID }}.dkr.ecr.{{ .Region }}.amazonaws.com/deltastreaminc/v2/oci/api-server
  provider: aws
  ref:
    tag: 0.0.7-schema-version-check
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: schema-migration-test
  namespace: schema-test-migrate
spec:
  sourceRef:
    kind: OCIRepository
    name: schema-migration-test
    namespace: schema-test-migrate
  interval: 60m
  retryInterval: 5m
  path: ./schema-test-migrate/default
  prune: true
  timeout: 10m
  wait: true
  images:
  - name: api-server
    newName: {{ .DsEcrAccountID }}.dkr.ecr.{{ .Region }}.amazonaws.com/deltastreaminc/v2/services/api-server
    newTag: {{ .ApiServerNewVersion }}
  postBuild:
    substitute:
      test_rds_host: {{ .test_pg_host }}
      rdsCACertsSecret: {{ .rdsCACertsSecret }}
      region: {{ .Region }}
      stack: stage
      topology: ds
      infraID: kd8j38
      cloud: aws
      resourceID: mint
