apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: schema-migration-test
  namespace: schema-test-migrate
spec:
  interval: 5m
  url: oci://{{ .DsEcrAccountID }}.dkr.ecr.{{ .Region }}.amazonaws.com/deltastreaminc/v2/oci/api-server
  provider: aws
  ref:
    tag: 0.0.28-schema-version-check
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: schema-migration-test
  namespace: schema-test-migrate
spec:
  sourceRef:
    kind: OCIRepository
    name: schema-migration-test
    namespace: schema-test-migrate
  interval: 60m
  retryInterval: 5m
  path: ./schema-test-migrate/default
  prune: true
  timeout: 10m
  wait: true
  images:
  - name: deltastreaminc/v2/services/api-server
    newName: {{ .DsEcrAccountID }}.dkr.ecr.{{ .Region }}.amazonaws.com/deltastreaminc/v2/services/api-server
    newTag: {{ .ApiServerNewVersion }}
  postBuild:
    substitute:
      test_rds_host: {{ .test_pg_host }}
      rdsCACertsSecret: {{ .rdsCACertsSecret }}
      test_rds_master_externalsecret: {{ .test_rds_master_externalsecret }}
      stack: {{ .stack }}
      infraID: {{ .infraID }}
      region: {{ .Region }}
      resourceID: {{ .resourceID }}
      test_db_name: {{ .test_db_name }}
      topology: {{ .topology }}
      cloud: {{ .cloud }}
      dsEcrAccountID: "{{ .DsEcrAccountID }}"
      apiServerNewVersion: "0.3.3691-00afe022f"
      test_rds_schema_user: "{{ .test_rds_schema_user }}"
