apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: schema-migration-test
  namespace: schema-test-migrate
spec:
  interval: 5m
  url: oci://{{ .DsEcrAccountID }}.dkr.ecr.{{ .Region }}.amazonaws.com/deltastreaminc/v2/oci/api-server
  provider: aws
  ref:
    tag: 0.0.4-schema-version-check
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: schema-migration-test
  namespace: schema-test-migrate
spec:
  sourceRef:
    kind: OCIRepository
    name: schema-migration-test
    namespace: schema-test-migrate
  interval: 60m
  retryInterval: 5m
  path: ./schema-test-migrate/default
  prune: true
  wait: true
  timeout: 2m
  images:
  - name: api-server
    newName: {{ .DsEcrAccountID }}.dkr.ecr.{{ .Region }}.amazonaws.com/deltastreaminc/v2/services/api-server
    newTag: 0.0.4-schema-version-check
  postBuild:
    substitute:
      test_pg_host: {{ .test_pg_host }}

