apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- network-policies.yaml
patches:
- patch: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: source-controller
      namespace: flux-system
      annotations:
        eks.amazonaws.com/role-arn: "{{ .EksReaderRoleArn }}"
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --no-remote-bases=true
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --concurrent=10
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --requeue-dependency=5s
    - op: add
      path: /spec/template/spec/tolerations
      value:
        - key: CriticalAddonsOnly
          operator: Exists
  target:
    kind: Deployment
    name: "kustomize-controller"
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --concurrent=10
    - op: add
      path: /spec/template/spec/tolerations
      value:
        - key: CriticalAddonsOnly
          operator: Exists
  target:
    kind: Deployment
    name: "helm-controller"
- patch: |
    - op: add
      path: /spec/template/spec/tolerations
      value:
        - key: CriticalAddonsOnly
          operator: Exists
  target:
    kind: Deployment
    name: "source-controller"
- patch: |
    - op: add
      path: /spec/template/spec/tolerations
      value:
        - key: CriticalAddonsOnly
          operator: Exists
  target:
    kind: Deployment
    name: "notification-controller"
- patch: |
    - op: add
      path: /spec/serviceAccountName
      value: kustomize-controller
  target:
    kind: Kustomization
    name: "flux-system"
namespace: flux-system
